<a href="https://colab.research.google.com/github/carmc99/Introduction-to-IA-course/blob/intro%2Fpython/01_BASIC_STRUCTURES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Lab 1


In [ ]:
import numpy as np

v1 = np.array([1,2,3,4])

# the log of each element of the vector
print ( "the log   =", np.log(v1)  )

# the mean of all elements of the vector
print ( "the mean  =",  np.mean(v1)  )

# multiply all elements of a vector with a scalar
print ("times two =", 2*v1)


the log   = [0.         0.69314718 1.09861229 1.38629436]
the mean  = 2.5
times two = [2 4 6 8]


(numpy.ndarray, float)

## Task 01. Accuracy

Compute the percentage of correct predictions **accuracy** (see [here](https://en.wikipedia.org/wiki/Sensitivity_and_specificity#Definitions)) for the following model output (`predicted`) and ground truth (`actual`).

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

**CHALLENGE**: use Python with [`sklearn.metrics.accuracy_score`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score)


Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again.

In [ ]:
from sklearn.metrics import accuracy_score

def accuracy(actual, predicted):
  return accuracy_score(actual, predicted)
  

In [ ]:
import numpy as np
t1_actual    = np.random.randint(2, size=20)
t1_predicted = np.abs(t1_actual*(np.random.random(size=20)>(np.random.random()*.9+.05)).astype(int))
print ("actual   ", ", ".join([str(i) for i in t1_actual]))
print ("predicted", ", ".join([str(i) for i in t1_predicted]))

print(accuracy(t1_actual, t1_predicted))

actual    0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1
predicted 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0
0.85


## Task 2: Sensitivity

Compute the sensitivity metric [aka the _True Positive Rate_ or _Recall_ see [Sensitivity on Wikipedia](https://en.wikipedia.org/wiki/Sensitivity_and_specificity)] for the following model output (`predicted`) and ground truth (`actual`)

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

**Challenge**: Use Python [`sklearn.metrics.recall_score`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html)


Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again.

In [ ]:
from sklearn.metrics import recall_score

def sensitivity(actual, predicted):
  return recall_score(actual, predicted)

In [ ]:
import numpy as np
t2_predicted = np.random.randint(2, size=20)
t2_actual = np.random.randint(2, size=20)
t2_predicted[np.argwhere(t2_actual==1)[0][0]]=0
print ("actual   ", ", ".join([str(i) for i in t2_actual]))
print ("predicted", ", ".join([str(i) for i in t2_predicted]))

print(sensitivity(t2_actual, t2_predicted))

actual    0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1
predicted 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1


## Task 3: Evaluation in New York City Taxi Trip Duration Kaggle Competition

Understand the data and the evaluation metric (**Root Mean Squared Logarithmic Error**, RMSLE) of the following Kaggle competition

- [https://www.kaggle.com/c/nyc-taxi-trip-duration/](https://www.kaggle.com/c/nyc-taxi-trip-duration/)

Observe that this competition is a **regression task** as we are measuring the difference in prediction with respect to the actual.

For instance, the following model predictions and ground truth:

    actual    [66 37 22]
    predicted [79 51 67]
    
produce a **RMSLE** of 0.66 aprox.

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

**Challenge**: For python use numpy function `np.log` or `np.log1p`

Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again.

In [ ]:

def rmsle(actual, predicted):
    log_diff = np.log1p(predicted) - np.log1p(actual)
    print(log_diff)
    return np.sqrt(np.mean(log_diff ** 2))  # np.mean average

In [ ]:
import numpy as np
t2_predicted = np.random.randint(2, size=20)
t2_actual = np.random.randint(2, size=20)
t2_predicted[np.argwhere(t2_actual==1)[0][0]]=0
print ("actual   ", ", ".join([str(i) for i in t2_actual]))
print ("predicted", ", ".join([str(i) for i in t2_predicted]))

rmsle(t2_actual, t2_predicted)

actual    0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0
predicted 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0
[ 0.69314718 -0.69314718  0.69314718  0.          0.          0.
  0.          0.69314718  0.         -0.69314718  0.69314718  0.
 -0.69314718  0.69314718 -0.69314718  0.          0.         -0.69314718
  0.          0.        ]


0.49012907173427356

## Task 4: Evaluation in Shelter Animal Outcomes Kaggle Competition

Understand the data and the evaluation metric (**Multiclass Logaritmic Loss**, _logloss_) of the following Kaggle competition

- [https://www.kaggle.com/c/shelter-animal-outcomes/](https://www.kaggle.com/c/shelter-animal-outcomes/)

Observe that this competition is a **classification task with 5 classes** and, for each item, the model produces a probability for each class. Classes are numbered from 0 to 4.

For instance, the following represents the model output for **three items**

    [[0.17 0.27 0.03 0.31 0.21]
     [0.09 0.44 0.02 0.15 0.3 ]
     [0.26 0.18 0.25 0.2  0.11]]
     
Where the classes with gretest probability assigned by the model are 

- class 3 for the first item (with 0.31 probability) 
- class 1 for the second item (with 0.44 probability)
- class 0 for the third item (with 0.26 probability)

The class labels are expressed as a similar matrix, but with 0/1
For instance, the ground truth for the corresponding three items above, could be:

    [[0 0 0 1 0]
     [0 0 1 0 0]
     [1 0 0 0 0]]

and will produce a **logloss** of approx 2.14

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

In [ ]:
import numpy as np

def logloss(actual, predicted):
  logP = np.log(predicted)
  y = actual * logP
  avg = -(1/len(actual)) * y.sum()
  return avg

In [ ]:
import numpy as np

t4_predicted = np.random.random(size=(7,5)).T+0.5
t4_predicted = np.round((t4_predicted/np.sum(t4_predicted,axis=0)),2).T

t4_actual = np.eye(5)[np.random.randint(5,size=len(t4_predicted))].astype(int)

print ("actual")
print (t4_actual)
print ("\npredicted")
print (t4_predicted)

logloss([[0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0]], [[0.17, 0.27, 0.03, 0.31, 0.21],
 [0.09, 0.44, 0.02, 0.15, 0.3 ],
 [0.26, 0.18, 0.25, 0.2, 0.11]])

actual
[[1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]

predicted
[[0.16 0.18 0.17 0.26 0.23]
 [0.19 0.2  0.13 0.17 0.3 ]
 [0.18 0.15 0.3  0.19 0.18]
 [0.27 0.18 0.2  0.1  0.25]
 [0.12 0.29 0.26 0.17 0.17]
 [0.22 0.17 0.15 0.21 0.25]
 [0.28 0.14 0.25 0.21 0.11]]


2.1434265449659

### Lab 2.1

## Task 1: Palindrome

Determine whether an integer number $n$ is a palindrome, this is, if it is the same number when read left to right and when read right to left. Return `True` if so, otherwise return `False`.

**Execution example**

```python
>>> palindromo(n=3456543)
True

>>> palindromo(n=543)
False
```

**hint**: transform it into string, reverse it and check equality

**challenge**: use one single line of code

In [ ]:
def palindromo(n): # assume n is an integer
    n = str(n) # convert number to str
    if(n[::-1] == n): # slice the string
      return True
    return False

In [ ]:
print (palindromo(12321))
print (palindromo(12322))

True
False


## Task 2: Money Change

En este ejercicio, su programa recibirá un monto entre 1 y 99 centavos de Dolar, Escriba un metodo que retorne en una lista, cuantas monedas son necesarias para devolverle a alguien dicho valor, si únicamente se cuenta con monedas de 1, 10 y 25 centavos. La lista debe entregarse de la siguiente manera:

In this task your function will receive an amount between 1 and 99 cents and will have to return a list with three numbers [$n_1$, $n_{10}$, $n_{25}$], specifying how many coins of 1, 10 and 25 cents are required to obtain the given amonut. We only have coints of 1, 10 and 25 cents. There are no other kinds of coins.

If the amount given is less than 1 or more than 99 you must return `None`.

**Execution example**

```python
>>> change_money(n=55)
[5,0,2]

>>> change_money(n=200)
None

>>> change_money(n=47)
[2,2,1]
```

**hint**: use `\\` for integer division


In [ ]:
def change_money(n):
    r=[0,0,0] #recall: r[0]== n_1, r[1]== n_10 y r[2]== n_25 
    if n>99 or n<1: return None
    while n > 0:
      if(n // 25 > 0):
        n -= 25
        r[2] += 1
      elif(n // 10 > 0):
        n-=10
        r[1] += 1
      else:
        n-=1
        r[0] += 1
        
    return r

In [ ]:
print(change_money(n=55))
print(change_money(n=200))
print(change_money(n=47))


[5, 0, 2]
None
[2, 2, 1]


## Task 3: Fibonacci

Complete the function below so that given an integer $n$ it computes the $n^{th}$ term of the Fibonacci series:

$$ f_n = f_{n-1}+f_{n-2}$$ 

Where $$f_0=0 \:\:\text{ y }\:\:f_1=1 $$ so that: $$f_2=1+0=1$$ $$f_3=1+1=2$$ $$f_4=2+1=3$$ and so on

### Execution example 
```python

>>> fibonacci(10)
55

>>> fibonacci(36)
14930352
```

In [ ]:
def fibonacci(n):
    f0=0
    f1=1
    suma=0
    i = 0
    while i < n:
      suma = f0 + f1
      f1 = f0
      f0 = suma
      i += 1
    return suma

In [ ]:
fibonacci(10), fibonacci(36)

(55, 14930352)

## Task 4: Perfect number

complete the following function so that it accepts an integer $n$ and returns `True` if $n$ is a perfect number and `False` otherwise.

A perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself. For instance $6=3+2+1$ 

See https://en.wikipedia.org/wiki/Perfect_number

**Execution example**
```python
>>> perfecto(6)
True

>>> perfecto(51)
False

>>> perfecto(496)
True
```
**hint**: make a loop of all numbers up to $n$ and use the modulus operator `%` to identify which are the divisors, then sum them up.

In [ ]:
def perfecto(n):
    i = 1
    sum = 0
    while i < n:
      if(n%i == 0):
        sum += i
      i += 1

    if(n == sum):
      return True
    return False

In [ ]:
perfecto(6), perfecto(51), perfecto(496)

(True, False, True)

### Lab 2.2 Numpy

## Task 1: Cauchy Matrix


Given two vectors (1D `numpy` arrays), $x$ and $y$, build the Cauchy Matrix:


$$C_{ij}=\:\: \frac{1}{x_i-y_j}$$

See https://en.wikipedia.org/wiki/Cauchy_matrix, the elements of the matrix are the results of substracting the correpsonding positions in the $x$ and $y$ vectors where the rows correspond to $x$ and the columns to $y$.

**NOTE**: if there is any division by zero, you must raise a `ValueError` exception.

**HINT**: create a matrix with zeros with the desired output shape, use broadcasting of $x$ as row vector, and then broadcasting of $y$ as column vector with `reshape(-1,1)`

**CHALLENGE**: build a function with maximum four lines of code, including checking for zeros and raising the exception.

**Execution example**

```python
>> x = np.array([45, 31, 67, 75, 54])
>> y = np.array([17,  7, 15, 15, 18])
>> cauchy(c,y)
array([[0.03571429, 0.02631579, 0.03333333, 0.03333333, 0.03703704],
       [0.07142857, 0.04166667, 0.0625    , 0.0625    , 0.07692308],
       [0.02      , 0.01666667, 0.01923077, 0.01923077, 0.02040816],
       [0.01724138, 0.01470588, 0.01666667, 0.01666667, 0.01754386],
       [0.02702703, 0.0212766 , 0.02564103, 0.02564103, 0.02777778]])
```

In [ ]:
def cauchy(x, y):
    result = []
    row = []
    for i in range(len(x)):
      for j in range(len(y)):
        elementX = x[i]
        elementY = y[j]
        diff = 1 / (elementX - elementY)
        if(diff == 0):
          raise ValueError()
        row.append(diff)
      result.append(row)
      row = []

    return result

In [ ]:
import numpy as np

x = np.array([45, 31, 67, 75, 54])
y = np.array([17,  7, 15, 15, 18])
cauchy(x,y)

[[0.03571428571428571,
  0.02631578947368421,
  0.03333333333333333,
  0.03333333333333333,
  0.037037037037037035],
 [0.07142857142857142,
  0.041666666666666664,
  0.0625,
  0.0625,
  0.07692307692307693],
 [0.02,
  0.016666666666666666,
  0.019230769230769232,
  0.019230769230769232,
  0.02040816326530612],
 [0.017241379310344827,
  0.014705882352941176,
  0.016666666666666666,
  0.016666666666666666,
  0.017543859649122806],
 [0.02702702702702703,
  0.02127659574468085,
  0.02564102564102564,
  0.02564102564102564,
  0.027777777777777776]]

## Task 2: Position of closest scalar

Given a 1D vector $x$, find the position of the closest element to $v$


**Execution example**:

```python
>> x=np.arange(25,55,3)
>> minimo(x,34)
3
```

**HINT**: use [`np.argmin`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html)

**CHALLENGE**: solve it with one line of code

In [ ]:
def minimo(x,v):
    minArray = np.abs(x-v) # halla el valor absoluto de cada item del array, con el resultado de la diferencia del item y el valor de v
    minIdx = np.argmin(minArray) # retorna el indice del valor minimo en el array
    return minIdx

In [ ]:
x = np.arange(25,55,3)
v = 34
minimo(x,v)

## Task 3: Substracting row mean

Given a matrix, your function must return a new one with the same dimensions in which each component is substracted the mean of its own row.


**Execution example**
```python
>> X = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
>> media(X)
array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])
```

**HINT**: use broadcasting

**CHALLENGE**: solve it with one line of code

In [86]:
import numpy as np

def media(X):
    r = []
    for i in range(len(X)):
      media = (X - np.mean(X[i]))
      r.append(media[i].tolist())
    return r

In [87]:
X = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
media(X)

[-1.  0.  1.]
[-1.  0.  1.]
[-1.  0.  1.]


[[-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0]]

## Task 4: Double the diagonal

Complete the following function such that it returns the same matrix received in $X$ but with its diagonal multiplied by 2. Assume $X$ is a square matrix (with the same number of rows and columns).

**Execution example**

```python
>> X = np.array([[79, 45, 67,  8, 37],
>>               [47, 40,  5, 79, 86],
>>               [72, 25, 44, 45, 22],
>>               [12, 85,  8, 53, 28],
>>               [ 4, 37, 36, 40, 16]])
>> 
>> doublediag(X)

array([[158.,  45.,  67.,   8.,  37.],
       [ 47.,  80.,   5.,  79.,  86.],
       [ 72.,  25.,  88.,  45.,  22.],
       [ 12.,  85.,   8., 106.,  28.],
       [  4.,  37.,  36.,  40.,  32.]])
```

**HINT**: use [`np.eye`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)

**CHALLENGE**: solve with one line of code

In [127]:
import numpy as np

def doublediag(X):
    r = np.eye(len(X[0]), len(X)) * 2 # Genera una matrix con diagonal de unos
    r[r == 0] = 1 # Convierte los ceros en 1
    r = X * r
    return r

In [128]:
X = np.array([[79, 45, 67,  8, 37],
              [47, 40,  5, 79, 86],
              [72, 25, 44, 45, 22],
              [12, 85,  8, 53, 28],
              [ 4, 37, 36, 40, 16]])
doublediag(X)

array([[158.,  45.,  67.,   8.,  37.],
       [ 47.,  80.,   5.,  79.,  86.],
       [ 72.,  25.,  88.,  45.,  22.],
       [ 12.,  85.,   8., 106.,  28.],
       [  4.,  37.,  36.,  40.,  32.]])