<a href="https://colab.research.google.com/github/carmc99/Introduction-to-IA-course/blob/intro%2Fpython/01_BASIC_STRUCTURES.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Lab 1


In [ ]:
import numpy as np

v1 = np.array([1,2,3,4])

# the log of each element of the vector
print ( "the log   =", np.log(v1)  )

# the mean of all elements of the vector
print ( "the mean  =",  np.mean(v1)  )

# multiply all elements of a vector with a scalar
print ("times two =", 2*v1)


the log   = [0.         0.69314718 1.09861229 1.38629436]
the mean  = 2.5
times two = [2 4 6 8]


(numpy.ndarray, float)

## Task 01. Accuracy

Compute the percentage of correct predictions **accuracy** (see [here](https://en.wikipedia.org/wiki/Sensitivity_and_specificity#Definitions)) for the following model output (`predicted`) and ground truth (`actual`).

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

**CHALLENGE**: use Python with [`sklearn.metrics.accuracy_score`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html#sklearn.metrics.accuracy_score)


Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again.

In [ ]:
from sklearn.metrics import accuracy_score

def accuracy(actual, predicted):
  return accuracy_score(actual, predicted)
  

In [ ]:
import numpy as np
t1_actual    = np.random.randint(2, size=20)
t1_predicted = np.abs(t1_actual*(np.random.random(size=20)>(np.random.random()*.9+.05)).astype(int))
print ("actual   ", ", ".join([str(i) for i in t1_actual]))
print ("predicted", ", ".join([str(i) for i in t1_predicted]))

print(accuracy(t1_actual, t1_predicted))

actual    0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1
predicted 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0
0.85


## Task 2: Sensitivity

Compute the sensitivity metric [aka the _True Positive Rate_ or _Recall_ see [Sensitivity on Wikipedia](https://en.wikipedia.org/wiki/Sensitivity_and_specificity)] for the following model output (`predicted`) and ground truth (`actual`)

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

**Challenge**: Use Python [`sklearn.metrics.recall_score`](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.recall_score.html)


Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again.

In [ ]:
from sklearn.metrics import recall_score

def sensitivity(actual, predicted):
  return recall_score(actual, predicted)

In [ ]:
import numpy as np
t2_predicted = np.random.randint(2, size=20)
t2_actual = np.random.randint(2, size=20)
t2_predicted[np.argwhere(t2_actual==1)[0][0]]=0
print ("actual   ", ", ".join([str(i) for i in t2_actual]))
print ("predicted", ", ".join([str(i) for i in t2_predicted]))

print(sensitivity(t2_actual, t2_predicted))

actual    0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1
predicted 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1


## Task 3: Evaluation in New York City Taxi Trip Duration Kaggle Competition

Understand the data and the evaluation metric (**Root Mean Squared Logarithmic Error**, RMSLE) of the following Kaggle competition

- [https://www.kaggle.com/c/nyc-taxi-trip-duration/](https://www.kaggle.com/c/nyc-taxi-trip-duration/)

Observe that this competition is a **regression task** as we are measuring the difference in prediction with respect to the actual.

For instance, the following model predictions and ground truth:

    actual    [66 37 22]
    predicted [79 51 67]
    
produce a **RMSLE** of 0.66 aprox.

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

**Challenge**: For python use numpy function `np.log` or `np.log1p`

Observe that every time you execute the following cell, **a different set of values** is generated. You will have to compute the metric **for the values that you see**. If you run the cell again you will have to compute your metric value again.

In [ ]:

def rmsle(actual, predicted):
    log_diff = np.log1p(predicted) - np.log1p(actual)
    print(log_diff)
    return np.sqrt(np.mean(log_diff ** 2))  # np.mean average

In [ ]:
import numpy as np
t2_predicted = np.random.randint(2, size=20)
t2_actual = np.random.randint(2, size=20)
t2_predicted[np.argwhere(t2_actual==1)[0][0]]=0
print ("actual   ", ", ".join([str(i) for i in t2_actual]))
print ("predicted", ", ".join([str(i) for i in t2_predicted]))

rmsle(t2_actual, t2_predicted)

actual    0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0
predicted 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0
[ 0.69314718 -0.69314718  0.69314718  0.          0.          0.
  0.          0.69314718  0.         -0.69314718  0.69314718  0.
 -0.69314718  0.69314718 -0.69314718  0.          0.         -0.69314718
  0.          0.        ]


0.49012907173427356

## Task 4: Evaluation in Shelter Animal Outcomes Kaggle Competition

Understand the data and the evaluation metric (**Multiclass Logaritmic Loss**, _logloss_) of the following Kaggle competition

- [https://www.kaggle.com/c/shelter-animal-outcomes/](https://www.kaggle.com/c/shelter-animal-outcomes/)

Observe that this competition is a **classification task with 5 classes** and, for each item, the model produces a probability for each class. Classes are numbered from 0 to 4.

For instance, the following represents the model output for **three items**

    [[0.17 0.27 0.03 0.31 0.21]
     [0.09 0.44 0.02 0.15 0.3 ]
     [0.26 0.18 0.25 0.2  0.11]]
     
Where the classes with gretest probability assigned by the model are 

- class 3 for the first item (with 0.31 probability) 
- class 1 for the second item (with 0.44 probability)
- class 0 for the third item (with 0.26 probability)

The class labels are expressed as a similar matrix, but with 0/1
For instance, the ground truth for the corresponding three items above, could be:

    [[0 0 0 1 0]
     [0 0 1 0 0]
     [1 0 0 0 0]]

and will produce a **logloss** of approx 2.14

Execute the following cell to generate the data from which you must compute the metric. You may compute the metric implementing python code, or manually, or copy/pasting the actual and predicted data in Excel, etc.

In [ ]:
import numpy as np

def logloss(actual, predicted):
  logP = np.log(predicted)
  y = actual * logP
  avg = -(1/len(actual)) * y.sum()
  return avg

In [ ]:
import numpy as np

t4_predicted = np.random.random(size=(7,5)).T+0.5
t4_predicted = np.round((t4_predicted/np.sum(t4_predicted,axis=0)),2).T

t4_actual = np.eye(5)[np.random.randint(5,size=len(t4_predicted))].astype(int)

print ("actual")
print (t4_actual)
print ("\npredicted")
print (t4_predicted)

logloss([[0, 0, 0, 1, 0],
 [0, 0, 1, 0, 0],
 [1, 0, 0, 0, 0]], [[0.17, 0.27, 0.03, 0.31, 0.21],
 [0.09, 0.44, 0.02, 0.15, 0.3 ],
 [0.26, 0.18, 0.25, 0.2, 0.11]])

actual
[[1 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]
 [0 0 0 1 0]]

predicted
[[0.16 0.18 0.17 0.26 0.23]
 [0.19 0.2  0.13 0.17 0.3 ]
 [0.18 0.15 0.3  0.19 0.18]
 [0.27 0.18 0.2  0.1  0.25]
 [0.12 0.29 0.26 0.17 0.17]
 [0.22 0.17 0.15 0.21 0.25]
 [0.28 0.14 0.25 0.21 0.11]]


2.1434265449659

### Lab 2.1

## Task 1: Palindrome

Determine whether an integer number $n$ is a palindrome, this is, if it is the same number when read left to right and when read right to left. Return `True` if so, otherwise return `False`.

**Execution example**

```python
>>> palindromo(n=3456543)
True

>>> palindromo(n=543)
False
```

**hint**: transform it into string, reverse it and check equality

**challenge**: use one single line of code

In [ ]:
def palindromo(n): # assume n is an integer
    n = str(n) # convert number to str
    if(n[::-1] == n): # slice the string
      return True
    return False

In [ ]:
print (palindromo(12321))
print (palindromo(12322))

True
False


## Task 2: Money Change

En este ejercicio, su programa recibirá un monto entre 1 y 99 centavos de Dolar, Escriba un metodo que retorne en una lista, cuantas monedas son necesarias para devolverle a alguien dicho valor, si únicamente se cuenta con monedas de 1, 10 y 25 centavos. La lista debe entregarse de la siguiente manera:

In this task your function will receive an amount between 1 and 99 cents and will have to return a list with three numbers [$n_1$, $n_{10}$, $n_{25}$], specifying how many coins of 1, 10 and 25 cents are required to obtain the given amonut. We only have coints of 1, 10 and 25 cents. There are no other kinds of coins.

If the amount given is less than 1 or more than 99 you must return `None`.

**Execution example**

```python
>>> change_money(n=55)
[5,0,2]

>>> change_money(n=200)
None

>>> change_money(n=47)
[2,2,1]
```

**hint**: use `\\` for integer division


In [ ]:
def change_money(n):
    r=[0,0,0] #recall: r[0]== n_1, r[1]== n_10 y r[2]== n_25 
    if n>99 or n<1: return None
    while n > 0:
      if(n // 25 > 0):
        n -= 25
        r[2] += 1
      elif(n // 10 > 0):
        n-=10
        r[1] += 1
      else:
        n-=1
        r[0] += 1
        
    return r

In [ ]:
print(change_money(n=55))
print(change_money(n=200))
print(change_money(n=47))


[5, 0, 2]
None
[2, 2, 1]


## Task 3: Fibonacci

Complete the function below so that given an integer $n$ it computes the $n^{th}$ term of the Fibonacci series:

$$ f_n = f_{n-1}+f_{n-2}$$ 

Where $$f_0=0 \:\:\text{ y }\:\:f_1=1 $$ so that: $$f_2=1+0=1$$ $$f_3=1+1=2$$ $$f_4=2+1=3$$ and so on

### Execution example 
```python

>>> fibonacci(10)
55

>>> fibonacci(36)
14930352
```

In [ ]:
def fibonacci(n):
    f0=0
    f1=1
    suma=0
    i = 0
    while i < n:
      suma = f0 + f1
      f1 = f0
      f0 = suma
      i += 1
    return suma

In [ ]:
fibonacci(10), fibonacci(36)

(55, 14930352)

## Task 4: Perfect number

complete the following function so that it accepts an integer $n$ and returns `True` if $n$ is a perfect number and `False` otherwise.

A perfect number is a positive integer that is equal to the sum of its positive divisors, excluding the number itself. For instance $6=3+2+1$ 

See https://en.wikipedia.org/wiki/Perfect_number

**Execution example**
```python
>>> perfecto(6)
True

>>> perfecto(51)
False

>>> perfecto(496)
True
```
**hint**: make a loop of all numbers up to $n$ and use the modulus operator `%` to identify which are the divisors, then sum them up.

In [ ]:
def perfecto(n):
    i = 1
    sum = 0
    while i < n:
      if(n%i == 0):
        sum += i
      i += 1

    if(n == sum):
      return True
    return False

In [ ]:
perfecto(6), perfecto(51), perfecto(496)

(True, False, True)

### Lab 2.2 Numpy

## Task 1: Cauchy Matrix


Given two vectors (1D `numpy` arrays), $x$ and $y$, build the Cauchy Matrix:


$$C_{ij}=\:\: \frac{1}{x_i-y_j}$$

See https://en.wikipedia.org/wiki/Cauchy_matrix, the elements of the matrix are the results of substracting the correpsonding positions in the $x$ and $y$ vectors where the rows correspond to $x$ and the columns to $y$.

**NOTE**: if there is any division by zero, you must raise a `ValueError` exception.

**HINT**: create a matrix with zeros with the desired output shape, use broadcasting of $x$ as row vector, and then broadcasting of $y$ as column vector with `reshape(-1,1)`

**CHALLENGE**: build a function with maximum four lines of code, including checking for zeros and raising the exception.

**Execution example**

```python
>> x = np.array([45, 31, 67, 75, 54])
>> y = np.array([17,  7, 15, 15, 18])
>> cauchy(c,y)
array([[0.03571429, 0.02631579, 0.03333333, 0.03333333, 0.03703704],
       [0.07142857, 0.04166667, 0.0625    , 0.0625    , 0.07692308],
       [0.02      , 0.01666667, 0.01923077, 0.01923077, 0.02040816],
       [0.01724138, 0.01470588, 0.01666667, 0.01666667, 0.01754386],
       [0.02702703, 0.0212766 , 0.02564103, 0.02564103, 0.02777778]])
```

In [ ]:
def cauchy(x, y):
    result = []
    row = []
    for i in range(len(x)):
      for j in range(len(y)):
        elementX = x[i]
        elementY = y[j]
        diff = 1 / (elementX - elementY)
        if(diff == 0):
          raise ValueError()
        row.append(diff)
      result.append(row)
      row = []

    return result

In [ ]:
import numpy as np

x = np.array([45, 31, 67, 75, 54])
y = np.array([17,  7, 15, 15, 18])
cauchy(x,y)

[[0.03571428571428571,
  0.02631578947368421,
  0.03333333333333333,
  0.03333333333333333,
  0.037037037037037035],
 [0.07142857142857142,
  0.041666666666666664,
  0.0625,
  0.0625,
  0.07692307692307693],
 [0.02,
  0.016666666666666666,
  0.019230769230769232,
  0.019230769230769232,
  0.02040816326530612],
 [0.017241379310344827,
  0.014705882352941176,
  0.016666666666666666,
  0.016666666666666666,
  0.017543859649122806],
 [0.02702702702702703,
  0.02127659574468085,
  0.02564102564102564,
  0.02564102564102564,
  0.027777777777777776]]

## Task 2: Position of closest scalar

Given a 1D vector $x$, find the position of the closest element to $v$


**Execution example**:

```python
>> x=np.arange(25,55,3)
>> minimo(x,34)
3
```

**HINT**: use [`np.argmin`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html)

**CHALLENGE**: solve it with one line of code

In [ ]:
def minimo(x,v):
    minArray = np.abs(x-v) # halla el valor absoluto de cada item del array, con el resultado de la diferencia del item y el valor de v
    minIdx = np.argmin(minArray) # retorna el indice del valor minimo en el array
    return minIdx

In [ ]:
x = np.arange(25,55,3)
v = 34
minimo(x,v)

## Task 3: Substracting row mean

Given a matrix, your function must return a new one with the same dimensions in which each component is substracted the mean of its own row.


**Execution example**
```python
>> X = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
>> media(X)
array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])
```

**HINT**: use broadcasting

**CHALLENGE**: solve it with one line of code

In [ ]:
import numpy as np

def media(X):
    r = []
    for i in range(len(X)):
      media = (X - np.mean(X[i]))
      r.append(media[i].tolist())
    return r

In [ ]:
X = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
media(X)

[-1.  0.  1.]
[-1.  0.  1.]
[-1.  0.  1.]


[[-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0], [-1.0, 0.0, 1.0]]

## Task 4: Double the diagonal

Complete the following function such that it returns the same matrix received in $X$ but with its diagonal multiplied by 2. Assume $X$ is a square matrix (with the same number of rows and columns).

**Execution example**

```python
>> X = np.array([[79, 45, 67,  8, 37],
>>               [47, 40,  5, 79, 86],
>>               [72, 25, 44, 45, 22],
>>               [12, 85,  8, 53, 28],
>>               [ 4, 37, 36, 40, 16]])
>> 
>> doublediag(X)

array([[158.,  45.,  67.,   8.,  37.],
       [ 47.,  80.,   5.,  79.,  86.],
       [ 72.,  25.,  88.,  45.,  22.],
       [ 12.,  85.,   8., 106.,  28.],
       [  4.,  37.,  36.,  40.,  32.]])
```

**HINT**: use [`np.eye`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.eye.html)

**CHALLENGE**: solve with one line of code

In [ ]:
import numpy as np

def doublediag(X):
    r = np.eye(len(X[0]), len(X)) * 2 # Genera una matrix con diagonal de unos
    r[r == 0] = 1 # Convierte los ceros en 1
    r = X * r
    return r

In [ ]:
X = np.array([[79, 45, 67,  8, 37],
              [47, 40,  5, 79, 86],
              [72, 25, 44, 45, 22],
              [12, 85,  8, 53, 28],
              [ 4, 37, 36, 40, 16]])
doublediag(X)

array([[158.,  45.,  67.,   8.,  37.],
       [ 47.,  80.,   5.,  79.,  86.],
       [ 72.,  25.,  88.,  45.,  22.],
       [ 12.,  85.,   8., 106.,  28.],
       [  4.,  37.,  36.,  40.,  32.]])

# LAB 02.03 - Pandas

In [6]:
import numpy as np
import pandas as pd

## Task 1: Extract data

we have a dataframe of items with a price and, **sometimes**, with an extra column (`margin`).

You will have to complete a function that will **filter** the dataframe selecting the rows:

- whose price is > 100
- **OR** whose margin is >10, if the column `margin` is present

your function must return **A LIST** with the item ids of the selected rows

For instance, with the following dataframe

             price  category
    itemid                  
    56556   108.15       2.0
    73065    83.54       2.0
    36619   114.42       0.0
    73414    82.94       0.0
    13410   115.13       2.0
    66153    91.50       1.0
    77380    85.82       0.0
    73249    95.95       0.0
    11654   100.22       2.0
    11972    77.16       1.0

your must return the following list:

     [56556, 36619, 13410, 11654]
     
But if you get the following dataframe

             price  category  margin
    itemid                          
    39059    98.11       0.0   11.04
    19526    98.11       1.0   11.25
    78176    94.34       1.0   10.51
    50948   102.37       1.0   10.77
    12111    98.07       1.0    8.50
    56191    98.53       1.0   11.65
    38887    91.49       2.0   11.24
    77915   117.30       0.0    8.64
    55010    96.13       0.0    8.95
    45925    98.59       1.0   10.45
    
you must return the following list

    [39059, 19526, 78176, 50948, 56191, 38887, 77915, 45925]

In [3]:
def create_df(missing=False, n=10):
    itemid   = np.random.randint(100000, size=n)+1000
    category = np.random.randint(3, size=n)
    price    = np.round(np.random.normal(loc=100, scale=10, size=n),2)
    margin   = np.round(np.random.normal(loc=10, scale=1, size=n),2)
    
    if missing:
        nmissing = np.random.randint(len(price)//2)+2                                     
        price[np.random.permutation(len(price))[:nmissing]] = np.nan
    
    d = pd.DataFrame(np.r_[[price, category, margin]].T, index=itemid, columns=["price", "category", "margin"])
    d.index.name="itemid"
    if np.random.random()>.5:
        d = d[d.columns[:2]]
        
    return d

In [ ]:
def select_items(df):
    # make sure to make a copy in case you modify the original df
    df = df.copy()
    result = []
    condition1 = (df.price > 100)
    if "margin" in df.columns:
      condition2 = (df.margin > 10)
      r1 = (df[condition1 | condition2]).copy()
      return r1.index.tolist()
    else:
      r2 = (df[condition1]).copy()
      return r2.index.tolist()
    result = []
    return result

In [ ]:
d = create_df()
d

price  category  margin
itemid                          
18609   102.14       0.0    9.47
93054    89.65       2.0    7.97
71838    90.97       2.0    9.98
30404    88.52       0.0   10.10
93568    73.04       0.0   10.03
72032    98.21       2.0    9.16
93248   112.61       2.0    9.72
1325     95.14       0.0    9.36
61060   107.68       0.0    9.33
44045   115.32       2.0    9.96

In [ ]:
select_items(d)

[18609, 30404, 93568, 93248, 61060, 44045]

## Task 2: Group statistics

Complete the following function so that it returns a dataframe with the average, max and min **prices** per category. 

For instance, for the following dataframe

             price  category  margin
    itemid                          
    17946    93.85       1.0   10.64
    61190    91.72       1.0    9.76
    39639   100.16       1.0   10.67
    17791   110.44       2.0    9.65
    7333    101.05       1.0    9.69
    77362   122.33       0.0   11.14
    92646   108.13       2.0   10.58
    27797    85.52       2.0   10.88
    31746    97.56       0.0    9.75
    12355   101.04       2.0    9.51
    
you should return the following dataframe

                 media  maximo  minimo
    categoria                         
    0         109.9450  122.33  97.56
    1          96.6950  101.05  91.72
    2         101.2825  110.44  85.52
    
observe that your result
- must not be a **multilevel** columnset.
- the column names and the index name must be **exactly** as in the example.
- the **index** must be of type **int**.

In [ ]:
import numpy as np

def get_stats(df):
    # make sure to make a copy in case you modify the original df
    df = df.copy()

    df['min_price'] = df.groupby('category')['price'].transform('min')
    df['max_price'] = df.groupby('category')['price'].transform('max')
    df['avg_price'] = df.groupby('category')['price'].transform('mean')

    df['category'] = df['category'].astype(int)
    agg_df = df.rename(columns={'category': 'categoria'})
    agg_df = agg_df.groupby('categoria').agg({'price': ['mean', 'max', 'min']})


    # Renombramos las columnas

    agg_df.columns = ['media', 'maximo', 'minimo']

    return agg_df

In [ ]:
d = create_df()
d

price  category
itemid                  
58120   105.31       0.0
96318   103.92       2.0
3200     96.34       2.0
90704   103.43       1.0
89198    65.33       2.0
80607    97.72       1.0
59372   117.22       2.0
79400   106.80       0.0
18228   108.15       1.0
43041   110.37       2.0

In [ ]:
get_stats(d)

media  maximo  minimo
categoria                         
0          106.055  106.80  105.31
1          103.100  108.15   97.72
2           98.636  117.22   65.33

## Task 3: Fill in missing data

Fill in the missing data in the **price** column with the following procedure:

- compute the mean and std of the avaialable prices
- sample from a normal distribution with the computed mean and std (see [`np.random.normal`])(https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html), as many samples as missing data
- substitute the missing values with the samples

For instance, for this input dataframe:

             price  category  margin
    itemid                          
    18922      NaN       1.0   10.32
    69500   121.25       1.0   10.22
    76442    90.25       1.0   12.60
    33863   106.51       0.0   10.26
    15904    95.87       1.0   11.51
    41946   103.47       2.0    9.85
    85451    93.08       2.0    9.56
    70028   116.68       1.0    9.11
    26860      NaN       2.0    9.71
    12807    91.48       0.0    9.77
    
your solution might be similar to this (not exactly the same as you will be sampling data):


                 price  category  margin
    itemid                              
    18922    97.441188       1.0   10.32
    69500   121.250000       1.0   10.22
    76442    90.250000       1.0   12.60
    33863   106.510000       0.0   10.26
    15904    95.870000       1.0   11.51
    41946   103.470000       2.0    9.85
    85451    93.080000       2.0    9.56
    70028   116.680000       1.0    9.11
    26860   103.294843       2.0    9.71
    12807    91.480000       0.0    9.77
    
    
**WARN**: your function must not modify the original dataframe, make a copy of the input dataframe, fill the values in the copy and return it.

**HINT**: use the [`isna()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isna.html) method of a dataframe or a series.

In [19]:
def fillna(df):
    # make sure to make a copy in case you modify the original df
    isNaCount = 0
    df = df.copy()
    mean = df.price.mean()
    std = np.std(df.price)
    isNa = df.isna()
    for item in isNa.price:
      if(item):
        isNaCount += 1

    s = np.random.normal(mean, std, isNaCount)
    i = 0

    df.loc[df['price'].isnull(), 'price'] = s
    return df

In [8]:
d = create_df(missing=True)
d

price  category  margin
itemid                          
43666      NaN       1.0    8.41
6919       NaN       1.0    8.96
94365      NaN       2.0   10.29
47585   102.10       1.0   11.17
46300   102.61       1.0   11.57
26030   111.99       1.0    9.78
36985    98.05       0.0   10.60
61633    92.93       0.0    9.70
22039      NaN       0.0    9.48
6953       NaN       0.0    9.33

In [20]:
fillna(d)

price  category  margin
itemid                              
43666    92.710578       1.0    8.41
6919     95.556313       1.0    8.96
94365    96.658613       2.0   10.29
47585   102.100000       1.0   11.17
46300   102.610000       1.0   11.57
26030   111.990000       1.0    9.78
36985    98.050000       0.0   10.60
61633    92.930000       0.0    9.70
22039   100.832183       0.0    9.48
6953    100.768369       0.0    9.33

### LAB 02.04 - Card trick

## Setup 

make sure to **watch the corresponding video** to understand the card trick.

### create a deck for a given configuration

The following function returns a list of **card names**. The `shuffle` argument is self evident. We use two letters as an arbitrary card name so that we have enough names for large configurations.

In [ ]:

def create_deck(n_heaps, cards_per_heap, shuffle=False):
    n_cards = n_heaps * cards_per_heap
    
    chars = [chr(i) for i in np.arange(26)+65]
    names = [i+j for i,j in itertools.product(chars, chars)]    

    assert n_cards < len(names), "cannot have more than %d cards"%len(name)
    
    c = np.r_[names[:n_cards]]
    if shuffle:
        c = np.random.permutation(c)
    return c

In [ ]:
create_deck(n_heaps=3, cards_per_heap=10, shuffle=False)

In [ ]:
create_deck(n_heaps=3, cards_per_heap=7, shuffle=True)

In [ ]:
create_deck(n_heaps=3, cards_per_heap=10, shuffle=True)

pick a card
the following function randomly picks a card from a deck

In [ ]:
def pick_card(c):
    return np.random.choice(c)

In [ ]:
c = create_deck(n_heaps=3, cards_per_heap=7, shuffle=True)
n = pick_card(c)
n

## Task 1. Make the heaps

Complete the following funcion so that given desk (as a list returned by `create_deck`) distributes the cards in `n_heaps` according to the procedure of the card trick shown in the video.

The heaps must be a list of `n_heaps` lists, each one with `len(c)/n_heaps` card names.

`n_heaps` will be an odd number (so that later we can put the chosen heap in the middle of the others), and must be a divisor of the total number of cards in the deck (so that all heaps have the same number of cards)

For instance, 

    >>> n_heaps = 3
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
    >>> h = make_heaps(c, n_heaps)
    >>> print("deck", c)
    >>> print("heaps")
    >>> h   

    deck ['AA' 'AB' 'AC' 'AD' 'AE' 'AF' 'AG' 'AH' 'AI' 'AJ' 'AK' 'AL' 'AM' 'AN'
     'AO' 'AP' 'AQ' 'AR' 'AS' 'AT' 'AU']
    heaps
    [['AA', 'AD', 'AG', 'AJ', 'AM', 'AP', 'AS'],
     ['AB', 'AE', 'AH', 'AK', 'AN', 'AQ', 'AT'],
     ['AC', 'AF', 'AI', 'AL', 'AO', 'AR', 'AU']]
  
or also

    >>> n_heaps = 5
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=3, shuffle=True)
    >>> h = make_heaps(c, n_heaps)
    >>> print("deck", c)
    >>> print("heaps")
    >>> h
    
    deck ['AA' 'AJ' 'AM' 'AK' 'AH' 'AF' 'AD' 'AN' 'AB' 'AC' 'AG' 'AE' 'AL' 'AI'
     'AO']
    heaps
    [['AA', 'AF', 'AG'],
     ['AJ', 'AD', 'AE'],
     ['AM', 'AN', 'AL'],
     ['AK', 'AB', 'AI'],
     ['AH', 'AC', 'AO']]

In [ ]:
def make_heaps(c, n_heaps=3):
    assert n_heaps%2==1, "must have an odd number of heaps"
    assert len(c)%n_heaps==0, "the length of the deck must be a multiple of the number of heaps"
    
    h = ... # YOUR CODE HERE
    return h


manually check your code

In [ ]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
h = make_heaps(c, n_heaps)

print("deck", c)
print("heaps")
h


In [ ]:
n_heaps = 5
c = create_deck(n_heaps=n_heaps, cards_per_heap=3, shuffle=True)
h = make_heaps(c, n_heaps)

print("deck", c)
print("heaps")
h


## Task 2: Organize the heaps

Complete the following funcion so that given a set of heaps (such as the ones returned by the function of the previous task) and a card name:

1. Finds what is the heap that contains the card
1. Makes randomly two groups of `n_heaps//2` heaps of the remaining heaps
   - if `n_heaps=3` this will be two groups of one heap each, since `3//2=1`
   - if `n_heaps=5`, it will be two groups of two heaps each, since `5//2=2`
   - etc. (observe `//` is the integer division)
1. Concatenates the cards in one group with the cards in the heap containing the given card name. with the cards of the second group

For example

    >>> n_heaps = 3
    >>> c = create_deck(n_heaps=n_heaps, cards_per_heap=7, shuffle=True)
    >>> n = pick_card(c)
    >>> print ("card picked", n)
    >>> h = make_heaps(c, n_heaps)
    >>> h
    
    card picked AD
    [['AP', 'AC', 'AE', 'AO', 'AQ', 'AF', 'AM'],
     ['AN', 'AT', 'AB', 'AJ', 'AU', 'AI', 'AS'],
     ['AR', 'AD', 'AA', 'AG', 'AH', 'AL', 'AK']]
    
    
    >>> new_c = collect_heaps(h, n)
    >>> print (new_c)
    
    ['AP', 'AC', 'AE', 'AO', 'AQ', 'AF', 'AM', 'AR', 'AD', 'AA', 'AG', 'AH', 'AL', 'AK', 'AN', 'AT', 'AB', 'AJ', 'AU', 'AI', 'AS']

In [ ]:
def collect_heaps(h, n):
    
    r = ... # YOUR CODE HERE
    
    return r            

In [ ]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=7, shuffle=True)
n = pick_card(c)
print ("card picked", n)
h = make_heaps(c, n_heaps)
h

In [ ]:
new_c = collect_heaps(h, n)
print (new_c)

## Task 3: Run the card trick

Complete the following function such that, when given a a deck of cards `c`, and picked card `n` and a number of heaps `n_heaps`, returns the position of the picked card after doing three times the collect. The position number **must start at zero**.

For instance:

- For `n_heaps=3` and `cards_per_heap=7`, the final position will always be 10 (which is 11 if you start counting at 1)
- For `n_heaps=3` and `cards_per_heap=4`, the final position will be sometimes 5 and sometimes 6 depending on the position of the picked card on the initial deck.
- For `n_heaps=5` and `cards_per_heap=3`, the final position will always be 7

**You must return an `int`**

In [ ]:
def run(c, n, n_heaps=3):
    r = ... # YOUR ANSWER HERE
    return r

In [ ]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=7)
picked = "AA"
print ("desk", c)
pos = run(c, picked, n_heaps=n_heaps)
print ("position of card %s is %d"%(picked, pos))

In [ ]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
picked = "AI"
print ("deck", c)
pos = run(c, picked, n_heaps=n_heaps)
print ("position of card %s is %d"%(picked, pos))

## Task 4: Run the trick using the math

Given:

- $n_h$: A number of heaps
- $c_h$: the number of cards per heap
- $i$: the position of a card 

The new position of the card after one cycle of making and collecting the heaps will be:

$$c_h(n_h\div2)+i\div n_h$$

Complete the following function so that it has the same functionality of the previous task, but applying only this formula without using the simulation above. You **MUST NOT ADD** or remove lines from the function skeleton below, **ONLY** fill in the `...`

You must get the same results as the previous task.

**HINT**: Use `np.argwhere` to get the initial position of the card in the deck

In [ ]:
def mrun(c, picked_card, n_heaps=3):
    assert len(c)%n_heaps==0, "the number of heaps must be a divisor of the deck length"
    
    ch = len(c)//n_heaps # cards per heap
    nh = n_heaps
    
    i = ... # initial position of the card on the deck c
    p1 = ...  # the position of the card after the first round
    p2 = ...  # the position of the card after the second round
    p3 = ...  # the position of the card after the last round
    
    return p3

In [ ]:
n_heaps = 3
c = create_deck(n_heaps=n_heaps, cards_per_heap=4)
picked = "AI"
print ("deck", c)
pos = mrun(c, picked, n_heaps=n_heaps)
print ("position of card %s is %d"%(picked, pos))